### PR TITLE
unit test exec_command and friends w.r.t. migration device state

### PR DESCRIPTION
**Pull request by tmakatos**
Signed-off-by: Thanos Makatos <thanos.makatos@nutanix.com>

### CODE REVIEW

**Comment by tmakatos** [comment]
TODO fill in how to repro bug with `make test CC=gcc BUILD_TYPE=rel`

**Comment by swapnili** [comment]
> Using `make test CC=gcc BUILD_TYPE=rel`
> commit [c592301](https://github.com/nutanix/libvfio-user/commit/c5923013fc309a985d8b19c1f95a63ccf7134639) works, while commit [0e034d6](https://github.com/nutanix/libvfio-user/commit/0e034d6385cb1eac9eef7750dece96415936203f) doesn't.
> @jlevon @swapnili any ideas why this breaks?!

Looks like you fixed the compilation error and not the unit-test is failing https://github.com/nutanix/libvfio-user/pull/346/checks?check_run_id=1912354953

**Comment by tmakatos** [comment]
> > Using `make test CC=gcc BUILD_TYPE=rel`
> > commit [c592301](https://github.com/nutanix/libvfio-user/commit/c5923013fc309a985d8b19c1f95a63ccf7134639) works, while commit [0e034d6](https://github.com/nutanix/libvfio-user/commit/0e034d6385cb1eac9eef7750dece96415936203f) doesn't.
> > @jlevon @swapnili any ideas why this breaks?!
> 
> Looks like you fixed the compilation error and not the unit-test is failing https://github.com/nutanix/libvfio-user/pull/346/checks?check_run_id=1912354953

I wasn't clear, let me clarify: if compiled with `make CC=gcc BUILD_TYPE=rel`, commit 0e034d6385cb1eac9eef7750dece96415936203f fails the `test_cmd_allowed_when_stopped_and_copying` unit test:
```
[ RUN      ] test_cmd_allowed_when_stopped_and_copying
[  ERROR   ] --- r
[   LINE   ] --- /root/src/libvfio-user/test/unit-tests.c:1436: error: Failure!
```
This doesn't happen if it's compiled with `BUILD_TYPE=dbg`. The previous commit, c5923013fc309a985d8b19c1f95a63ccf7134639, works correctly. Looking at the "bad" commit (0e034d6385cb1eac9eef7750dece96415936203f), I don't understand why this change would break the unit test, I've tried to debug this and in unit test `test_cmd_allowed_when_stopped_and_copying` and for `i=0` `cmd_allowed_when_stopped_and_copying` returns `1` while the expression inside it is correctly evaluated to `0`. This doesn't make any sense.

**Comment by tmakatos** [comment]
I managed to create a minimal repro and it turns out the problem is not providing a function declaration for the `__real_` functions, since they get resolved anyway. My suspicion is that we automatically get a function declaretion that default to return type `int` (4 bytes) whereas we return `bool` (1 byte). Will confirm that this is the case for libvfio-user and will also provide the minimal repro.

**Comment by jlevon** [comment]
cf https://github.com/nutanix/libvfio-user/issues/342 right?

**Comment by tmakatos** [comment]
> cf #342 right?

"cf" ?

**Comment by tmakatos** [comment]
> Will confirm that this is the case for libvfio-user and will also provide the minimal repro.

Indeed I get the same behavior in the unit tests, I've sent an email to the GCC mailing list to clarify, I think this results in legitimate undefined behavior, so I guess we should fix #342.

**Comment by tmakatos** [comment]
#349 should fix the bug.

**Review by swapnili — APPROVED** [review]

**Pull request merged**
