### PR TITLE
use MSG_NOSIGNAL for sendmsg()

### PR DESCRIPTION
**Pull request by jlevon**

### CODE REVIEW

**Review by tmakatos — COMMENTED** [review]
Why do we need this?

**Comment by jlevon** [comment]
I don't think it fixes a particular known issue, but generally, we shouldn't end up accidentally generating a SIGPIPE.

**Comment by tmakatos** [comment]
> I don't think it fixes a particular known issue, but generally, we shouldn't end up accidentally generating a SIGPIPE.

Fair enough, let's add this to the commit message for future reference.

**Comment by jlevon** [comment]
msg updated

**Review by tmakatos — APPROVED** [review]

**Pull request merged**
