### PR TITLE
don't use wrong buf offset for responding with PCI caps

### PR DESCRIPTION
**Pull request by tmakatos**
Signed-off-by: Thanos Makatos <thanos.makatos@nutanix.com>

### CODE REVIEW

**Review by jlevon — APPROVED** [review]
d'oh, thanks

**Comment by tmakatos** [comment]
> d'oh, thanks

This unit test fails: https://github.com/nutanix/libvfio-user/pull/355/checks?check_run_id=1953750278

Need to figure out why.

**Comment by jlevon** [comment]
Actually, I think this isn't right after all.

The bug is probably in pci_config_space_access() - in the loop, we are not moving "buf" along too, ie.. need:

393    buf += ret;

right?

**Review by jlevon — CHANGES_REQUESTED** [review]
as per comment

**Comment by tmakatos** [comment]
> Actually, I think this isn't right after all.
> 
> The bug is probably in pci_config_space_access() - in the loop, we are not moving "buf" along too, ie.. need:
> 
> 393 buf += ret;
> 
> right?

Maybe, this does allow the controller to progress further but I'm still getting errors, will continue debugging to see whether they're related.

**Review by jlevon — APPROVED** [review]
Thank you

**Pull request merged**
