### PR TITLE
Remove obsolete comment

### PR DESCRIPTION
**Pull request by swapnili**
Signed-off-by: Swapnil Ingle <swapnil.ingle@nutanix.com>

### CODE REVIEW

**Review by jlevon — COMMENTED** [review]
I this makes more sense to fix at the same time you remove sock_flags?

**Comment by swapnili** [comment]
This TODO sounds more like related to old transport_ops with enum (e.g VFU_TRANS_SOCK), looks like left over from old trans_ops cleanup.

**Comment by jlevon** [comment]
It's a moot point now, but as soon as you removed "sock_flags", the comment has nothing to refer to, so should really have been deleted at the same time. Anyway...

**Review by jlevon — APPROVED** [review]

**Comment by swapnili** [comment]
Yes maybe you are correct. Thanks

**Pull request merged**
