### PR TITLE
don't call DMA region add callabck when duplicate region is added

### PR DESCRIPTION
**Pull request by tmakatos**
Signed-off-by: Thanos Makatos <thanos.makatos@nutanix.com>

### CODE REVIEW

**Comment by jlevon** [comment]
I think I'm missing a bit of context here. Is this working around a qemu bug or something? 
Do we need something in the spec to say we are required to ignore duplicate exact mappings?

**Comment by jlevon** [comment]
Small typo in the commit title too

**Comment by tmakatos** [comment]
> Small typo in the commit title too

ok

**Comment by tmakatos** [comment]
> I think I'm missing a bit of context here. Is this working around a qemu bug or something?
> Do we need something in the spec to say we are required to ignore duplicate exact mappings?

QEMU sends two DMA map requests with the same DMA region. In our DMA code we don't re-add this region so I assumed that this behavior is legitimate. But I suppose your question makes sense, we need establish whether this behavior should be allowed by the spec.

**Comment by tmakatos** [comment]
> > I think I'm missing a bit of context here. Is this working around a qemu bug or something?
> > Do we need something in the spec to say we are required to ignore duplicate exact mappings?
> 
> QEMU sends two DMA map requests with the same DMA region. In our DMA code we don't re-add this region so I assumed that this behavior is legitimate. But I suppose your question makes sense, we need to establish whether this behavior should be allowed by the spec in the first place.

@jlevon we already cover this in the spec:
> A command to map over an existing region must be failed by the server with EEXIST set in error field in the reply.

So we need to tell JJ to fix it in QEMU. I'll implement a unit test for this.

**Comment by tmakatos** [comment]
Haven't hit this in a very long time, closing.

**Pull request closed without merging**
