### PR TITLE
->get_request(): return failure if not connected

### PR DESCRIPTION
**Pull request by jlevon**

### CODE REVIEW

**Review by tmakatos — COMMENTED** [review]
`get_msg` would still return the same error (via `recvmsg`), right?

**Comment by jlevon** [comment]
Yeah, but relying on recvmsg(-1) doing the wrong thing correctly, is a little gross.

**Comment by tmakatos** [comment]
> Yeah, but relying on recvmsg(-1) doing the wrong thing correctly, is a little gross.

Thought so, then can we add this to the commit message for future reference?

**Comment by jlevon** [comment]
done

**Review by tmakatos — APPROVED** [review]

**Pull request merged**
